version: "3"
services:
  app:
    container_name: hello-rust-app
    build:
      context: docker
      dockerfile: Dockerfile
    tty: true
    command: cargo watch -x run
    working_dir: /usr/local/hello-rust
    ports:
      - "8080:8080"
    volumes:
      - "./:/usr/local/hello-rust"

